### ISSUE TITLE
Silent Errors

### ISSUE THREAD

**Issue by trimitri** [b4b4r07/vim-sunset#1]
All error messages are muted by 658bb1de36abf2d660116d7db05fc209fd44b0cc .  This seems intentional, as there is a deliberate commit for it.

This gave me a hard time finding a typo I had in my config. Maybe consider a short note in the readme? Or even re-enable some of the error messages?

P.S. Thanks for caring for this project! By the looks of it you seem to be the current official maintainer of this little gem :-)

**Comment by babarot** [comment]
I cannot remember why I muted it, but it is welcome to turn it on!

**Comment by babarot** [comment]
Reverted
